- .gitignore
- Gemfile
- Makefile
- README.md
- bin/setup
Со старой командой ругался ярн и фикстуры. Гем `pg` убрал в прод группу, потому что из за него требовалась установка postgresql
> update setup command

- app/views/web/resumes/show.html.slim
> update resume show view

- app/controllers/web/resumes_controller.rb
- app/views/web/resumes/show.html.slim
- app/views/web/shared/_answer_form.html.slim
Поправил создание ответа и добавил отображение ответов
> Resume answer

- app/controllers/web/users_controller.rb
- app/helpers/application_helper.rb
- app/helpers/web/users_helper.rb
- app/views/layouts/shared/_nav.html.slim
- app/views/web/home/index.html.slim
- app/views/web/resumes/show.html.slim
- app/views/web/users/show.html.slim
- config/locales/ru.layouts.yml
- config/routes.rb
- test/controllers/web/users_controller_test.rb
> add users show

- app/controllers/web/account/resumes_controller.rb
- app/models/resume.rb
- app/views/web/account/resumes/_form.html.slim
- app/views/web/account/resumes/index.html.slim
- config/locales/ru.activerecord.yml
- config/locales/ru.views.yml
- config/routes.rb
Добавление стейта черновик и опубликовано в резюме
@amshkv
> add resume state

- app/controllers/web/account/profiles_controller.rb
- app/views/layouts/shared/_nav.html.slim
- app/views/web/account/profiles/_form.html.slim
- app/views/web/account/profiles/show.html.slim
- app/views/web/account/profiles/update.html.slim
- config/locales/ru.activerecord.yml
- config/locales/ru.helpers.yml
- config/locales/ru.views.yml
- config/routes.rb
- test/controllers/web/account/profiles_controller_test.rb
Перенес изменения из старой ветки
> add user profile

- test/fixtures/resume/works.yml
Ломалось при входе на последнее резюме
> fix fixtures

- app/controllers/web/users_controller.rb
- app/views/web/users/show.html.slim
- config/locales/ru.views.yml
Обновил немного вьюху, а то совсем пусто при входе на профиль
> User profile

- app/views/layouts/shared/_footer.html.slim
- config/locales/en.layouts.yml
- config/locales/ru.layouts.yml
> add footer

- app/controllers/web/users_controller.rb
поправил вывод списка резюме в профиле. выводились все, теперь выводятся только опубликованные
> fix user profile resume list

- app/views/web/account/profiles/_answers.html.slim
- app/views/web/account/profiles/_comments.html.slim
- app/views/web/account/profiles/_form.html.slim
- app/views/web/account/profiles/show.html.slim
Поправил вьюхи на страничке профиля.
> refactoring profiles tabs and content in tabs

- app/views/layouts/shared/_nav.html.slim
- config/locales/en.layouts.yml
- config/locales/ru.layouts.yml
Хочу сделать как на хекслете дропдаун. Несколько человек писали об этом.
"Мой профиль" будет открывать профиль так же как его видят другие, там будут резюме, ответы, комментарии.
Пункт "мои резюме" временный, потом его уберу т.к. резюме будут в профиле.
В пункте "настройки" пока будет только редактирование имени.
@amshkv
> add nav dropdown

- app/views/layouts/application.html.slim
- app/views/layouts/shared/_footer.html.slim
- app/views/layouts/shared/_nav.html.slim
@amshkv
Сделал, чтобы футер был внизу всегда и на мобилах не ломался хедер
Хедер
Футер
> footer to bottom

- app/controllers/web/home_controller.rb
- app/views/web/home/index.html.slim
- config/locales/en.views.yml
- config/locales/ru.views.yml
@amshkv
Сайдбар с последними 10 ответами
> add sidebar last asnwers

- app/controllers/web/account/resumes_controller.rb
- app/models/resume/education.rb
- app/views/schemas/_resume.json.jbuilder
- app/views/web/account/resumes/_education_fields.html.slim
- app/views/web/resumes/_information.html.slim
- config/locales/ru.activerecord.yml
- config/locales/simple_form.ru.yml
- db/migrate/20191004214449_add_resume_educations_description.rb
- db/migrate/20191004215126_fill_resume_educations_description_for_old_resumes.rb
- db/schema.rb
- test/factories/resume_educations.rb
- test/fixtures/resume/educations.yml
we don't really need all these details to be separate and these fields may not be suitable in some cases
> use description for education instead of institution, faculty

- app/views/schemas/_resume.json.jbuilder
https://schema.org/Organization
> fix works json schema

- app/controllers/web/resumes_controller.rb
example: freelance during several years but also had other jobs during that time
> sort works by end date

- app/views/web/account/resumes/_form.html.slim
no need to scroll and cannot misclick Delete
> move Add Work/Education button to the top

- app/controllers/web/account/resumes_controller.rb
- app/controllers/web/resumes_controller.rb
- app/models/resume.rb
- app/models/resume/education.rb
- app/models/resume/work.rb
- app/repositories/resume/education_repository.rb
- app/repositories/resume/work_repository.rb
- app/views/web/account/resumes/_form.html.slim
- test/controllers/web/account/resumes_controller_test.rb
should be always ordered: when editing, showing, ...
> always order works and educations by date

- app/views/web/account/resumes/_education_fields.html.slim
- app/views/web/account/resumes/_work_fields.html.slim
> make date selects in a row

- app/controllers/web/account/resumes_controller.rb
- app/models/resume.rb
- app/views/web/account/resumes/_form.html.slim
- test/controllers/web/account/resumes_controller_test.rb
- test/models/resume_test.rb
This change allows to hide(draft) previously published resume
> Add feature to hide public resume

- app/views/web/home/index.html.slim
- app/views/web/users/_resumes.html.slim
- app/views/web/users/show.html.slim
> add aligment author and date resume on bottom of card

- app/views/web/users/show.html.slim
> add nav-pills to profile tabs

- app/views/web/users/show.html.slim
- config/locales/ru.views.yml
за руби код не пинайте пожалуйста
> add new design on profile page

- app/views/layouts/shared/_nav.html.slim
> Enable dismissible alert for flash messages

- app/controllers/concerns/sparkpost.rb
- app/models/user.rb
- db/migrate/20191106050558_add_email_disabled_delivery_to_users.rb
- db/migrate/20191106051332_populate_email_disabled_delivery_in_users.rb
- db/schema.rb
- test/controllers/web/hooks/sparkposts_controller_test.rb
> add email disabled delivery to users

- app/views/layouts/shared/_menu.html.slim
> add date to last notifications

- app/controllers/application_controller.rb
- app/views/layouts/application.html.slim
- app/views/layouts/deps/_ga.html.slim
- app/views/layouts/deps/_gtm_body.html.slim
- app/views/layouts/deps/_gtm_head.html.slim
- app/views/layouts/shared/_head.html.slim
переменные в хероку я не добавлял, пока только прост аналитику и тег менеджер, без всяких  настроек
> add_analytics_and_tag_manager

- app/presenters/user_presenter.rb
This issue is the reason for failing CI builds
https://github.com/Hexlet/hexlet-cv/pull/169/checks?check_run_id=712770092
> Fix Rubocop issue

- app/models/resume/education.rb
- app/models/resume/work.rb
> [#180] fix resume remove work, education

- app/views/web/account/resumes/index.html.slim
> Moving the edit button

- app/views/web/shared/_resume_form.html.slim
https://rollbar.com/hexlet/hexlet-cv/items/42/
> fix resume form

- app/forms/web/account/resume_form.rb
- app/forms/web/admin/resume_form.rb
- app/views/web/resumes/_information.html.slim
- app/views/web/shared/_resume_form.html.slim
- config/locales/ru.activerecord.yml
- config/locales/ru.views.yml
- config/locales/simple_form.ru.yml
- db/migrate/20210202061301_add_contact_to_resume.rb
- db/schema.rb
- test/factories/resumes.rb
- test/factories/sequences.rb
- test/fixtures/resumes.yml
> add contact to resume

- public/robots.txt
> SEO: настройки индексации

- app/presenters/vacancy_presenter.rb
Там есть "от" и "до", поэтому тире не нужно
> change salary delimiter

- README.md
- app/views/web/admin/resumes/index.html.slim
- app/views/web/admin/vacancies/index.html.slim
- config/locales/en.yml
- config/locales/ru.activerecord.yml
- config/locales/ru.attributes.yml
- config/locales/ru.layouts.yml
- config/locales/ru.yml
- config/locales/simple_form.ru.yml
- db/schema.rb
closes #267 
* Поправил таблицу вакансий
* Добавил переводы
* В ридми добавил инструкцию для деплоя
Посмотреть здесь - https://fey-hexlet-cv.herokuapp.com/admin/vacancies 
login `full@email.com`
pass `password`
Скрины
[2021-09-21_22-19](https://user-images.githubusercontent.com/697178/134217753-c996ca67-e841-40ad-92d0-198daf423d91.png)
[2021-09-21_22-19_1](https://user-images.githubusercontent.com/697178/134217756-3ece6bb6-8146-4242-8693-d55d5f123b07.png)
> Improve admin vacanies panel

- app/controllers/web/resumes/answers_controller.rb
- test/controllers/web/resumes/answers_controller_test.rb
Хотел сделать а анкором на ответ, но не стал делать (если делать, то везде, как мне кажется, но с другой стороны это удобнее) ﻿
> add resume redirect

- app/controllers/web/account/vacancies_controller.rb
- app/controllers/web/admin/vacancies_controller.rb
- app/forms/web/account/vacancy_form.rb
- app/forms/web/admin/vacancy_form.rb
- app/presenters/vacancy_presenter.rb
- app/views/web/account/vacancies/edit.html.slim
- app/views/web/account/vacancies/new.html.slim
ЗП должно быть для всех обязательным, но мы в админке можем выбрать "по договоренности", будет отображаться вместо вилки "по договоренности"
https://fey-hexlet-cv.herokuapp.com/
full@email.com
password
> ЗП "по договоренности" из админки

- app/views/web/shared/_vacancy_filter.html.slim
> fix vacancy directions select (ref #308)

- Makefile
- README.md
Пара мелких фиксов, ошибки нашёл студент в процессе выполнения ДЗ deploy
> Fix makefile

- app/views/web/vacancies/show.html.slim
- config/locales/ru.views.yml
> Add notice for archived vacancy show view

- app/forms/web/account/vacancy_form.rb
- app/forms/web/admin/vacancy_form.rb
- db/migrate/20220217153127_strip_city_name_in_vacancies.rb
> Strip vacancy city name before save

- app/views/web/resumes/pdfs/base.slim
[тут](https://github.com/Hexlet/hexlet-cv/issues/327) просили добавить поля, добавил по аналогии с гитхабом
> [#327] Add hexlet_url and contact to resume pdf

- app/controllers/web/vacancy_filters_controller.rb
- config/initializers/constants.rb
- config/locales/ru.enumerize.yml
- config/locales/ru.views.yml
- config/locales/simple_form.ru.yml
issue - https://github.com/Hexlet/hexlet-cv/issues/331
Демо:
Фильтр вакансий - https://dkabanov-hexlet-cv.herokuapp.com/vacancy_filters/level-intern
Создание новой вакансии - https://dkabanov-hexlet-cv.herokuapp.com/account/vacancies/new
Для тестирования:
логин - admin@mail.com
пароль - password
1. Добавлен новый уровень Стажёр (intern) для формы создания новой вакансии и для фильтра по вакансиями
2. Поправлена логика вывода текстов для фильтра вакансий
> added new level intern

- config/locales/ru.views.yml
- test/fixtures/vacancies.yml
Доработки для SEO по [предыдущему ПР](https://github.com/Hexlet/hexlet-cv/pull/337)
Комментарий SEO-специалиста
> Здесь лучше так: Стажировки для Джуниор разработчиков
> Получается немного другой шаблон, не такой как в остальных таких же страницах
Демо:
Фильтр вакансий - https://dkabanov-hexlet-cv.herokuapp.com/vacancy_filters/level-intern
Создание новой вакансии - https://dkabanov-hexlet-cv.herokuapp.com/account/vacancies/new
Для тестирования:
логин - admin@mail.com
пароль - password
> issue/331 - improvements for seo

- app/models/resume/answer/comment.rb
- app/models/resume/comment.rb
- config/locales/simple_form.ru.yml
https://github.com/Hexlet/hexlet-cv/issues/356
> Изменил лимит символов комментария поста и ответа и соответствующие локали 

- app/views/web/resumes/_answer_requires.html.slim
- app/views/web/resumes/_comment_requires.html.slim
- app/views/web/resumes/show.html.slim
- config/locales/en.views.yml
- config/locales/ru.views.yml
Removed the ability for non-registered users to see and add comments to resumes.
User has to be registered in application in order to add comments and see others' people comments
> Hide comments from unauthorized users

- app/controllers/web/vacancies_controller.rb
- app/controllers/web/vacancy_filters_controller.rb
- app/models/vacancy.rb
- app/presenters/tag_presenter.rb
- app/views/web/shared/_vacancy_filter.html.slim
- app/views/web/vacancies/index.html.slim
- app/views/web/vacancy_filters/show.html.slim
Я тот пр за ресетил, я там что то на вертел, заново переделал.
> set sechnology sorting

- README.md
Исправлена ошибка в ссылке, из-за которой не выводилось изображение бейджа 'github-action-status'
> fix badge-link

- app/views/web/home/index.html.slim
результаты:
**320px**
**1366**
> [314] fix the alignment of blocks in the resume list

- app/models/vacancy.rb
- app/repositories/vacancy_repository.rb
- app/views/web/shared/_vacancies.html.slim
- app/views/web/vacancies/index.rss.builder
- db/migrate/20221118142445_add_published_at_to_vacancies.rb
- db/migrate/20221118143604_populate_vacancies_published_at.rb
- db/schema.rb
- test/controllers/web/admin/vacancies_controller_test.rb
- test/fixtures/vacancies.yml
- добавлено поле published_ad в vacancies
- в опциях assm модели Vacancy добавлена опция timestamps
- в vacanties index html & rss views created_at заменены на published_at
- изменена сортировка вакансий в index.html & rss
> Add tg and slack notice

- app/views/web/resumes/_comment_requires.html.slim
- app/views/web/resumes/show.html.slim
- config/locales/en.views.yml
- config/locales/ru.views.yml
По ишшусу https://github.com/Hexlet/hexlet-cv/issues/361 были скрыты комментарии И рекомендации. 
Рекомендации надо вернуть.
> show answers for guests

- app/views/web/resumes/show.html.slim
Вернул взад комментарии. 
Надо пообщаться с Кириллом, чтобы понять, будем ли мы скрывать это все или нет.
> bring back comments

- app/views/web/shared/_vacancies.html.slim
> fix display tags in vacansy

- app/views/web/shared/_resume_filter.html.slim
> add search for select resume

- Dockerfile
- docker-compose.yml
секция .env  не нужна из=за нее падали тесты, все подтягиваются через .dotenv
> fix run test in docker

- Gemfile.lock
- app/inputs/markdown_editor_input.rb
- app/javascript/entrypoints/application.js
- app/views/layouts/shared/_footer.html.slim
- app/views/layouts/shared/_head.html.slim
- app/views/web/shared/_resume_form.html.slim
- package-lock.json
- package.json
подскажите как сделать маркдаун эдитор с байндингом полей формы? У trix редактора это реализовано через веб компопнент
> Markdown editor

- app/views/layouts/web/admin/application.html.slim
- app/views/web/admin/home/index.html.slim
Добавил ссылки с Bootstrap для подключения Popper и Js
> [#453] fix dropmenu admin

- Dockerfile
- Makefile
- README.md
- docker-compose.yml
извиняюсь что сразу так не сделал, что то с хероку он тормозит, когда разделенно на два сервиса все стартует и останавливается быстрее
> fix docker

- app/javascript/entrypoints/application.js
- app/javascript/scripts/markdownEditor.js
- app/javascript/stylesheets/application.scss
вынес редактор в отдельный файл
> remove extra line breaks in text field

- app/controllers/concerns/locale_concern.rb
- app/controllers/web/application_controller.rb
- app/controllers/web/omniauth_callbacks_controller.rb
> Revert "fix redirect"

- app/controllers/web/account/resumes_controller.rb
- app/controllers/web/account/vacancies_controller.rb
- app/controllers/web/home_controller.rb
- app/controllers/web/locales_controller.rb
- app/controllers/web/resumes_controller.rb
- app/controllers/web/vacancies_controller.rb
- app/controllers/web/vacancy_filters_controller.rb
- app/models/user.rb
- app/repositories/concerns/with_locale_concern.rb
- app/repositories/resume_repository.rb
- app/repositories/vacancy_repository.rb
- db/migrate/20230330213046_add_locale_to_user.rb
- db/migrate/20230330213157_init_value_locale_to_user.rb
- db/schema.rb
- test/controllers/web/resumes_controller_test.rb
- test/fixtures/resumes.yml
- test/fixtures/users.yml
- test/fixtures/vacancies.yml
добавлю выборки еще в соответствии с локалью
> locale separation

- Gemfile
- Gemfile.lock
- app/helpers/application_helper.rb
- app/lib/markdown_renderer.rb
- app/views/web/shared/_answer.html.slim
- config/locales/en.views.yml
- config/locales/ru.views.yml
> fix displayed answers from openAI

- config/locales/simple_form.en.yml
> add locale for the placeholder

- config/locales/en.views.yml
> Fix header translation in edit comment recommendation section

- config/locales/ru.views.yml
Небольшое улучшение текста. Так как "проходить карьерный трек" - чето непонятное. При этом кнопка потом меняется на "продолжить".
> improve text "start career"

- app/controllers/web/admin/vacancies_controller.rb
https://github.com/Hexlet/hexlet-cv/issues/675
> Redirect to edit_admin_vacancy_path after save

- README.md
Исправлена опечатка в слове Prod**u**ction :) 
Чуток поправил описание setup'а, чтоб не сливалось в набор команд
> Fix README.md syntax errors

- config/application.rb
https://github.com/bkeepers/dotenv/pull/468
> fix deprecated warning

- Gemfile.lock
- app/controllers/web/account/vacancies_controller.rb
- app/views/web/account/vacancies/index.html.slim
Добавил сортировку по дате создания вакансий. Теперь все последние созданные вакансии будут отображаться в начале списка.
До
После
Возможно, стоит добавить поиск по состоянию?
> [#741] added sorting of vacancies by creation date
